Navbar y routing
scteam4/interactive-map pull request #8
Opened 2023-04-28 03:40 UTC by stevemen20020

Añadí la nav bar, haciéndola responsiva (más o menos espero que se vea bonita D:), de acuerdo a los lineamientos tanto de font como de colores que se veía en figma (ligma) (las fuentes las tienes que tener instaladas de manera local, no supe como subirlas directamente a la app, no sé si se pueda) y, además, el tutorial que seguí medio ciegamente terminé metiendo routing sin querer (literalmente soy la foto del buscador de youtube que dice "auxilio, accidentalmente construí una estantería" solo que ahora soy "auxilio, estaba escribiendo css y sin querer le añadí routing a mi app").

2023-04-28 03:59 UTC, Barraza44 commented on client/package.json
No estaba `react-router-dom` en la lista de dependencias. Es importante usar `npm install` porque así también se listan y añadir este archivo a los commits de git para que se puedan instalar las dependencias correctas en nuestras computadoras

2023-04-28 04:36 UTC, Barraza44 requested changes
Aquí los cambios que se deberían de hacer :)

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/NavBar.tsx
> +            <div className={`nav_items ${isOpen && "open"}`}>
En móvil, el menú no se cierra cuando oprimes una opción, debería cerrarse en automático.

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/index.tsx
> +export default Navbar;
Este `export` está sin utilizar, lo que sugiere que este componente no se usa. ¿Cuál es el propósito de un componente sin utilizar?

2023-04-28 04:36 UTC, Barraza44 commented on client/package.json
Aparentemente también faltan `styled-components` y `react-icons`

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/NavBar.css
> +@media (max-width:768px){
Si bien funciona, es preferible usar `min-width` para definir dentro de la media query las reglas para computadora, es decir ir de abajo hacia arriba en tamaños, es buena práctica

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/index.tsx
Utiliza [Prettier](https://prettier.io/) para darle formato al código y hacerlo más legibler

2023-04-28 04:36 UTC, Barraza44 commented on client/src/App.tsx
>    const [count, setCount] = useState(0)
Este estado sin usar se puede remover

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/NavItem.tsx
No le veo mucho uso a extraer esto como su propio componente pero no está mal tampoco

2023-04-28 04:36 UTC, Barraza44 commented on client/src/components/navbar/NavbarElements.tsx
¿Cuál es el uso de `styled-components` aquí si ya hay reglas CSS definidas antes? ¿O qué aportan estas reglas?

2023-07-20 08:33 UTC, stevemen20020 commented
Corregí todas las sugerencias del Diego, por tremendo estúpido ya que luego me dí cuenta que él las había corregido jASJAJSA tqm Dego, igualmente me vino bien la práctica, y sobre todo agradecer a Diego por sus comentarios. No sé si quieras revisar el nuevo commit que hice, o no sé si tenga que hacer un nuevo pull request, o qué, pero ahí la llevamos, tqm dego.

2023-07-30 04:35 UTC, Barraza44 approved these changes

2023-07-30 04:36 UTC, merged